update the mkconf file

diff --git a/usr/share/openmediavault/mkconf/mysql b/usr/share/openmediavault/mkconf/mysql
--- a/usr/share/openmediavault/mkconf/mysql
+++ b/usr/share/openmediavault/mkconf/mysql
@@ -21,67 +21,84 @@ set -e
 . /etc/default/openmediavault
 . /usr/share/openmediavault/scripts/helper-functions
 
-MY_CONFIG="/etc/mysql/my.cnf"
-MYSQL_CONFIG="/etc/mysql/conf.d/openmediavault-mysql.cnf"
-SQL_MANAGEMENT_SITE_CONF="/etc/nginx/openmediavault-webgui.d/openmediavault-mysql-management-site"
+MYSQL_MY_CONFIG="/etc/mysql/my.cnf"
+OMV_MYSQL_PLUGIN_CONFIG=${OMV_MYSQL_PLUGIN_CONFIG:-"/etc/mysql/conf.d/openmediavault-mysql.cnf"}
 
-# Enable/disable service
+detect_database_files()
+{
+    # Check for MySQL database files
+    if [ ! -e "${1}/ibdata1" ]; then
+        echo "Unable to find database files in ${1}"
+
+        return 3
+    fi
+
+    return 0
+}
+
+get_data_directory_from_config()
+{
+    cat ${1} | grep datadir | sed 's/datadir\s\+=\s\+//g'
+}
+
+# Generate configuration only if the service is enabled.
 if [ "$(omv_config_get "//services/mysql/enable")" != "1" ]; then
     exit 0
 fi
 
+# Get settings.
+data_sharedfolderref=$(omv_config_get "//services/mysql/data.sharedfolderref")
+data_directory="$(omv_get_sharedfolder_path "${data_directory}")"
+
 current_data_directory=""
 
-# Get current database location
-if [ -e "${MYSQL_CONFIG}" ]; then
-    current_data_directory="$(cat ${MYSQL_CONFIG} | grep datadir | sed 's/datadir\s\+=\s\+//g')"
+# Get the current database location.
+if [ -e "${OMV_MYSQL_PLUGIN_CONFIG}" ]; then
+    current_data_directory="$(get_data_directory_from_config ${OMV_MYSQL_PLUGIN_CONFIG})"
 else
-    # If not openmediavault mysql config, use standard mysql config file
-    if [ -e "${MY_CONFIG}" ]; then
-        current_data_directory="$(cat ${MY_CONFIG} | grep datadir | sed 's/datadir\s\+=\s\+//g')"
+    # If no openmediavault-mysql configuration exists, use the standard
+    # MySQL my.cnf file.
+    if [ -e "${MYSQL_MY_CONFIG}" ]; then
+        current_data_directory="$(get_data_directory_from_config ${MYSQL_MY_CONFIG})"
     else
         echo "Unable to get current database location"
         exit 2
     fi
 fi
 
-# Check for MySQL database files
-if [ ! -e "${current_data_directory}/ibdata1" ]; then
-    echo "Unable to find database files"
+# Check if any database files exists in the current data directory.
+if ! detect_database_files "${current_data_directory}" then
     exit 3
 fi
 
-# Get data location
-data_sharedfolderref=$(omv_config_get "//services/mysql/data.sharedfolderref")
-data_directory="$(omv_get_sharedfolder_path "${data_directory}")"
-
-# Create MySQL config file
-cat <<EOF > ${MYSQL_CONFIG}
-# Configuration for openmediavault-mysql
-
-[mysqld]
-EOF
-
+# Generate the MySQL configuration.
 xmlstarlet sel -t -m "//services/mysql" \
+    -o "# This configuration file automatically generated by openmediavault-mysql." -n \
+    -o "# Changes to this file will be automatically overwritten." -n -n \
+    -o "[mysqld]" -n \
     -i "enable_networking != 1" -o "skip-networking" -n -b \
     -i "port != ''" -v "concat('port = ', port)" -n -b \
     -i "bind_address != ''" -v "concat('bind-address = ', bind_address)" -n -b \
-    -o "datadir = ${data_directory}" -n -b \
+    -o "datadir = ${data_directory}" -n \
     -i "string-length(extra_options) > 0" -v "extra_options" -n -b \
-${OMV_CONFIG_FILE} | xmlstarlet unesc >> ${MYSQL_CONFIG}
+    ${OMV_CONFIG_FILE} | xmlstarlet unesc >> ${OMV_MYSQL_PLUGIN_CONFIG}
 
-chmod 644 ${MYSQL_CONFIG}
+# Set permissions on the configuration file.
+chmod 644 ${OMV_MYSQL_PLUGIN_CONFIG}
 
 if [ "${current_data_directory}" != "${data_directory}" ]; then
-    invoke-rc.d mysql stop
-
     # Take ownership of the shared folder.
     chown mysql:mysql "${data_directory}"
 
-    # Copy current data to the new directory and remove all files from the
-    # old.
-    cp -rfp ${current_data_directory}/* ${data_directory}/
-    rm -rf ${current_data_directory}/*
-
-    invoke-rc.d mysql start
+    # If the choosen directory already has database files, move the current
+    # ones. Otherwise use the existing files. This is useful if the user has
+    # reinstalled and wants to reuse the old files.
+    if ! detect_database_files "${data_directory}" ; then
+        # Copy current data to the new directory and remove all files from the
+        # old directory (but not the directory itself).
+        cp -rfp ${current_data_directory}/* ${data_directory}/
+        rm -rf ${current_data_directory}/*
+    fi
 fi
+
+exit 0
