some bugfixes

diff --git a/usr/share/openmediavault/mkconf/mysql b/usr/share/openmediavault/mkconf/mysql
--- a/usr/share/openmediavault/mkconf/mysql
+++ b/usr/share/openmediavault/mkconf/mysql
@@ -23,12 +23,19 @@ set -e
 
 MYSQL_MY_CONFIG="/etc/mysql/my.cnf"
 OMV_MYSQL_PLUGIN_CONFIG=${OMV_MYSQL_PLUGIN_CONFIG:-"/etc/mysql/conf.d/openmediavault-mysql.cnf"}
+OMV_MYSQL_PLUGIN_XPATH="//services/mysql"
 
 detect_database_files()
 {
+    if [ ! -d "${1}" ]; then
+        echo "Directory ${1} don't exist."
+
+        return 1
+    fi
+
     # Check for MySQL database files
     if [ ! -e "${1}/ibdata1" ]; then
-        echo "Unable to find database files in ${1}"
+        echo "Unable to find any database files in ${1}."
 
         return 3
     fi
@@ -38,17 +45,17 @@ detect_database_files()
 
 get_data_directory_from_config()
 {
-    cat ${1} | grep datadir | sed 's/datadir\s\+=\s\+//g'
+    cat "${1}" | grep datadir | sed 's/datadir\s\+=\s\+//g'
 }
 
 # Generate configuration only if the service is enabled.
-if [ "$(omv_config_get "//services/mysql/enable")" != "1" ]; then
+if [ "$(omv_config_get "${OMV_MYSQL_PLUGIN_XPATH}/enable")" != "1" ]; then
     exit 0
 fi
 
 # Get settings.
-data_sharedfolderref=$(omv_config_get "//services/mysql/data.sharedfolderref")
-data_directory="$(omv_get_sharedfolder_path "${data_directory}")"
+data_sharedfolderref=$(omv_config_get "${OMV_MYSQL_PLUGIN_XPATH}/data.sharedfolderref")
+data_directory="$(omv_get_sharedfolder_path "${data_sharedfolderref}")"
 
 current_data_directory=""
 
@@ -61,18 +68,18 @@ else
     if [ -e "${MYSQL_MY_CONFIG}" ]; then
         current_data_directory="$(get_data_directory_from_config ${MYSQL_MY_CONFIG})"
     else
-        echo "Unable to get current database location"
+        echo "Unable to get current database location."
         exit 2
     fi
 fi
 
 # Check if any database files exists in the current data directory.
-if ! detect_database_files "${current_data_directory}" then
+if ! detect_database_files "${current_data_directory}" ; then
     exit 3
 fi
 
 # Generate the MySQL configuration.
-xmlstarlet sel -t -m "//services/mysql" \
+xmlstarlet sel -t -m "${OMV_MYSQL_PLUGIN_XPATH}" \
     -o "# This configuration file automatically generated by openmediavault-mysql." -n \
     -o "# Changes to this file will be automatically overwritten." -n -n \
     -o "[mysqld]" -n \
@@ -81,15 +88,12 @@ xmlstarlet sel -t -m "//services/mysql" \
     -i "bind_address != ''" -v "concat('bind-address = ', bind_address)" -n -b \
     -o "datadir = ${data_directory}" -n \
     -i "string-length(extra_options) > 0" -v "extra_options" -n -b \
-    ${OMV_CONFIG_FILE} | xmlstarlet unesc >> ${OMV_MYSQL_PLUGIN_CONFIG}
+    ${OMV_CONFIG_FILE} | xmlstarlet unesc > ${OMV_MYSQL_PLUGIN_CONFIG}
 
 # Set permissions on the configuration file.
 chmod 644 ${OMV_MYSQL_PLUGIN_CONFIG}
 
 if [ "${current_data_directory}" != "${data_directory}" ]; then
-    # Take ownership of the shared folder.
-    chown mysql:mysql "${data_directory}"
-
     # If the choosen directory already has database files, move the current
     # ones. Otherwise use the existing files. This is useful if the user has
     # reinstalled and wants to reuse the old files.
@@ -99,6 +103,9 @@ if [ "${current_data_directory}" != "${data_directory}" ]; then
         cp -rfp ${current_data_directory}/* ${data_directory}/
         rm -rf ${current_data_directory}/*
     fi
+
+    # Take ownership of the shared folder.
+    chown -R mysql:mysql "${data_directory}"
 fi
 
 exit 0
