rewrite password reset to use mktemp and take password path arg
- Uses mktemp command.
- Takes an argument to the path to an password file.

diff --git a/usr/sbin/mysql-password b/usr/sbin/mysql-password
--- a/usr/sbin/mysql-password
+++ b/usr/sbin/mysql-password
@@ -21,43 +21,60 @@ set -e
 . /etc/default/openmediavault
 . /usr/share/openmediavault/scripts/helper-functions
 
-PWDFILE="/tmp/.openmediavault-mysql-reset-pwd"
-
-# Nothing to do if service is not enabled
-if [ "$(omv_config_get "//services/mysql/enable")" != "1" ]; then
+# Stop if the service is not enabled.
+if [ "$(omv_config_get "/config/services/mysql/enable")" != "1" ]; then
     exit 0
 fi
 
-if [ ! -f ${PWDFILE} ]; then
-    exit 2
+
+# Do error checks.
+if [ -z "${1}"]; then
+    echo "No password file path provided."
+    exit 1
 fi
 
-root_pass=`cat ${PWDFILE}`
-rm -f ${PWDFILE}
+mysql_root_password_file="${1}"
 
-PWFD="/tmp/.openmediavault-mysql"
-PWF="/tmp/.openmediavault-mysql/pw.$$"
+if [ ! -f ${mysql_root_password_file} ]; then
+    echo "Path to password file provided, but the file was not found."
+    exit 1
+fi
 
-[ -d ${PWFD} ] || mkdir ${PWFD}
-chown mysql:mysql ${PWFD}
-chmod 700 ${PWFD}
-echo ''>${PWF}
-chown mysql:mysql ${PWF}
-chmod 400 ${PWF}
+mysql_root_password=$(cat ${mysql_root_password_file})
 
-cat <<EOF >> ${PWF}
-UPDATE mysql.user SET Password=PASSWORD('${root_pass}') WHERE User='root';
+if [ -z ${mysql_root_password} ]; then
+    echo "Password file provided, but the file is empty."
+    exit 1
+fi
+
+
+# Create temporary init file and get the path.
+temp_init_file=$(su mysql -s /bin/sh -c mktemp)
+
+cat > ${temp_init_file} <<EOF
+UPDATE mysql.user SET Password=PASSWORD('${mysql_root_password}') WHERE User='root';
 FLUSH PRIVILEGES;
 EOF
 
-cat <<EOF > /etc/mysql/conf.d/pw.cnf
+
+# Create the tempory configuration file.
+temp_mysql_conf_file="/etc/mysql/conf.d/pw.cnf"
+
+cat > ${temp_mysql_conf_file} <<EOF
 [mysqld]
-init-file = ${PWF}
+init-file = ${temp_init_file}
 EOF
 
+
+# Restart service to reset the password.
 invoke-rc.d mysql restart
 
-rm -f /etc/mysql/conf.d/pw.cnf
-rm -f ${PWF}
-[ -d ${PWFD} ] && find ${PWFD} -type f -user mysql -exec rm {} \;
-rmdir ${PWFD}
+
+# Remove temporary files.
+if [ -f "${temp_mysql_conf_file}" ]; then
+    rm -f "${temp_mysql_conf_file}"
+fi
+
+if [ -f "${temp_init_file}" ]; then
+    rm -f "${temp_init_file}"
+fi
